kind: Deployment
apiVersion: apps/v1
metadata:
  name: teamspeak3-server
  namespace: teamspeak

spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: teamspeak3
    spec:
      volumes:
        - name: teamspeak-data
          persistentVolumeClaim:
            claimName: teamspeak3-pvc
      containers:
        - name: teamspeak3-server
          image: ertagh/teamspeak3-server:latest-box-predownloaded
          ports:
            - hostPort: 9987
              containerPort: 9987
              protocol: UDP
            - hostPort: 41144
              containerPort: 41144
              protocol: UDP
            - containerPort: 10011
              protocol: TCP
            - containerPort: 30033
              protocol: TCP
          env:
            - name: TIME_ZONE
              value: Europe/Rome
          resources: {}
          volumeMounts:
            - name: teamspeak-data
              mountPath: /teamspeak/save/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
