kind: Deployment
apiVersion: apps/v1
metadata:
  name: ts3-exporter-deployment
  namespace: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts3-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ts3-exporter
      annotations:
        prometheus.io/port: '9189'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: ts3-exporter
          image: quay.io/ricardbejarano/ts3exporter
          args:
            - '-remote=teamspeak3-server-int:10011'
            - '-user=serveradmin'
          ports:
            - containerPort: 9189
              protocol: TCP
          env:
            - name: SERVERQUERY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-query-pass
                  key: password
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
