kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: teamspeak3-data
  namespace: teamspeak
  annotations:
    argocd.argoproj.io/sync-options: CreateOrUpdate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm-provisioner
  volumeMode: Filesystem
