# deploy/bitwarden/Application-bitwarden-helmrepo.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
spec:
  project: default

  # --------------------------------------------
  # SORGENTE: chart proviene da un repository Helm esterno
  # --------------------------------------------
  source:
    repoURL: "https://charts.bitwarden.com/"
    chart: self-host
    targetRevision: "2025.5.1"
    helm:
      # Qui “dentro” metti TUTTO il contenuto del tuo values.yaml (override),
      # SENZA segreti in chiaro, facendo copia&incolla.
      values: |
        general:
          domain: "bitwarden.the.magesgate.com"
          ingress:
            enabled: true
            className: "nginx"
            annotations: {}
            labels: {}
            tls:
              name: "bitwarden-tls"                # Se usi TLS automatizzato con cert-manager, metti qui il nome del secret
              clusterIssuer: "letsencrypt-prod"

          disableUserRegistration: "false"
          admins: "service@magesgate.com"
          email:
            replyToEmail: "no-reply@magesgate.com"
            smtpHost: "smtp.magesgate.com"
            smtpPort: "587"
            smtpSsl: "true"
            smtpTrustServer: "false"
            smtpSslOverride: "false"
            smtpStartTls: "false"
          volumeAccessMode: "ReadWriteMany"
        sharedStorageClassName: "nfs-client"
        secrets:
          secretName: "bitwarden-secret"
        component:
          admin:
            image:
              name: ghcr.io/bitwarden/admin
            resources:
              requests:
                memory: "1Mi"
                cpu: "1m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            deploymentStrategy: RollingUpdate
          api:
            image:
              name: ghcr.io/bitwarden/api
            resources:
              requests:
                memory: "1Mi"
                cpu: "1m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            deploymentStrategy: RollingUpdate
          attachments:
            image:
              name: ghcr.io/bitwarden/attachments
            resources:
              requests:
                memory: "1Mi"
                cpu: "1m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            deploymentStrategy: RollingUpdate
          events:
            image:
              name: ghcr.io/bitwarden/events
            resources:
              requests:
                memory: "1Mi"
                cpu: "1m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            deploymentStrategy: RollingUpdate
          icons:
            image:
              name: ghcr.io/bitwarden/icons
            resources:
              requests:
                memory: "1Mi"
                cpu: "1m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            deploymentStrategy: RollingUpdate
          identity:
            image:
              name: ghcr.io/bitwarden/identity
            resources:
              requests:
                memory: "1Mi"
                cpu: "1m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            deploymentStrategy: RollingUpdate
          notifications:
            image:
              name: ghcr.io/bitwarden/notifications
            resources:
              requests:
                memory: "61i"
                cpu: "1m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            deploymentStrategy: RollingUpdate
          scim:
            enabled: false
            image:
              name: ghcr.io/bitwarden/scim
            resources:
              requests:
                memory: "1Mi"
                cpu: "1m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            deploymentStrategy: RollingUpdate
          sso:
            image:
              name: ghcr.io/bitwarden/sso
            resources:
              requests:
                memory: "1Mi"
                cpu: "1m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            deploymentStrategy: RollingUpdate
          web:
            image:
              name: ghcr.io/bitwarden/web
            resources:
              requests:
                memory: "1Mi"
                cpu: "1m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            deploymentStrategy: RollingUpdate

        volume:
          dataprotection:
            size: "1Gi"
            labels: {}
          attachments:
            size: "1Gi"
            labels: {}
          licenses:
            size: "1Gi"
            labels: {}
          logs:
            enabled: false
            size: "1Gi"
            labels: {}
          caCertificates:
            enabled: false
            configMapName: cacert

        database:
          enabled: true
          image:
            name: mcr.microsoft.com/mssql/server
            tag: 2022-CU11-ubuntu-22.04
          resources:
            requests:
              memory: 1Mi"
              cpu: "1m"
            limits:
              memory: "2G"
              cpu: "500m"
          volume:
            backups:
              size: "1Gi"
              labels: {}
            data:
              size: "10Gi"
              labels: {}
            log:
              size: "10Gi"
              labels: {}
          updateStrategy: OnDelete
  # --------------------------------------------

  destination:
    server: "https://kubernetes.default.svc"
    namespace: bitwarden

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
