
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-deployment
  namespace: argocd
spec:
  destination:
    namespace: bitwarden
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/bitwarden
    repoURL: https://github.com/gpillon/k8s-magesgate-deploy.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true