apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secco
  namespace: argocd
spec:
  destination:
    namespace: secco
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/secco
    repoURL: https://github.com/gpillon/k8s-magesgate-deploy.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
