kind: Deployment
apiVersion: apps/v1
metadata:
  name: factorio
  namespace: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: factorio
    spec:
      volumes:
        - name: save-data
          persistentVolumeClaim:
            claimName: factorio-saves
      containers:
        - name: factorio
          image: factoriotools/factorio:1.1.104
          ports:
            - name: game
              hostPort: 34197
              containerPort: 34197
              protocol: UDP
            - name: factorio-server
              containerPort: 27015
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: save-data
              mountPath: /factorio/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
