kind: Deployment
apiVersion: apps/v1
metadata:
  name: factorio
  namespace: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: factorio
    spec:
      initContainers:
      - name: copy-config
        image: busybox
        command:
          - sh
          - -c
          - |
            # Crea la cartella di destinazione (se non esiste) e copia il file
            mkdir -p /config && cp /secret/server-settings.json /config/server-settings.json && chown -R 1000:1000 /config
        volumeMounts:
          - name: secret-config
            mountPath: /secret
          - name: config
            mountPath: /config
      volumes:
        - name: save-data
          persistentVolumeClaim:
            claimName: factorio-saves
        - name: secret-config
          secret:
            secretName: factorio-settings
        - name: config
          emptyDir: {}
      containers:
        - name: factorio
          image: factoriotools/factorio:2.0.34
          ports:
            - name: game
              hostPort: 34197
              containerPort: 34197
              protocol: UDP
            - name: factorio-server
              containerPort: 27015
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: save-data
              mountPath: /factorio/
          - name: config
            mountPath: /factorio/config   
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
