kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: factorio-saves
  namespace: factorio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm-provisioner
  volumeMode: Filesystem
