apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java21-graalvm
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "FTBA"
        - name: FTB_MODPACK_ID
          value: "119"
        - name: MAX_MEMORY
          value: 4G
        - name: SERVER_NAME
          value: Magesgate.com
        - name: MOTD
          value: Where the magic Begins 
        ports:
        - containerPort: 25565
          hostPort: 25565
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-pvc
      nodeSelector:
        kubernetes.io/arch: arm64
  strategy:
    type: Recreate
